## Numpy Intuition


### Just a Refresher for np  intuition towards CV

In [1]:
import numpy as np 

In [2]:
mylst = [1,9,9]

In [3]:
type(mylst)

list

In [4]:
mynparray = np.array(mylst)

In [5]:
type(mynparray)

numpy.ndarray

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Note: 
1.) np.zeros , np.ones

In [29]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
print(arr)

[95 11 81 70 63 87 75  9 77 40]


In [30]:
arr2 = np.random.randint(0,100,10)
print(arr2)

[ 4 63 40 60 92 64  5 12 93 40]


In [33]:
print(arr.max())
print(arr.argmax())

95
0


In [34]:
print(arr.min())
print(arr.argmin())

9
7


In [39]:
arr.mean()

60.8

In [40]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [41]:
arr.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [42]:
matrix = np.arange(0,100).reshape(10,10)

In [43]:
print(matrix)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [50]:
row = 1
col = 0 


In [51]:
matrix[row,col]

10

In [52]:
matrix[4,6]

46

In [53]:
matrix[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [54]:
matrix[:2,]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [57]:
matrix[:,1].reshape(5,2)

array([[ 1, 11],
       [21, 31],
       [41, 51],
       [61, 71],
       [81, 91]])

In [58]:
matrix[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [60]:
matrix[0:3,0:2]

array([[ 0,  1],
       [10, 11],
       [20, 21]])

In [61]:
mynewmatrix = matrix.copy()

In [62]:
mynewmatrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [63]:
mynewmatrix[0:2,0:2] = 999

In [64]:
mynewmatrix

array([[999, 999,   2,   3,   4,   5,   6,   7,   8,   9],
       [999, 999,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])